import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopBar from "@/components/TopBar";
import './globalsFont.css'
import { AddPeopleProvider, BillProvider, ShowTotalProvider, VisibleCheck } from "@/components/context";
import TempMenuBottom from "../components/MenuBottom";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Teavel Pay",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <BillProvider>
          <AddPeopleProvider>
            <ShowTotalProvider>
              <VisibleCheck>
                <TopBar />
                  {children}
                <TempMenuBottom />
              </VisibleCheck>
            </ShowTotalProvider>
          </AddPeopleProvider>
        </BillProvider>
      </body>
    </html>
  );
}
